# Generated by Django 3.0.3 on 2020-03-10 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outof', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('combination', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('grade', models.IntegerField(default=0)),
                ('locker', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SIS.Locker')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIS.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIS.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('description', models.TextField(max_length=500)),
                ('students', models.TextField(default='', max_length=500)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIS.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIS.Courses'),
        ),
    ]
