# Generated by Django 3.0.3 on 2020-03-10 16:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('attendance', models.CharField(blank=True, choices=[('A', 'Absent'), ('P', 'Present'), ('E', 'Excused'), ('L', 'Late')], default='P', help_text='Attendance', max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIS.Courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIS.Student')),
            ],
        ),
    ]
