# Generated by Django 3.0.3 on 2020-03-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='code',
            field=models.CharField(default='', max_length=30),
        ),
    ]
