# Generated by Django 3.0.3 on 2020-03-10 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0003_auto_20200310_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
