# Generated by Django 3.0.3 on 2020-03-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0005_auto_20200310_1804'),
        ('SIS', '0003_auto_20200310_1705'),
    ]

    operations = [
    ]
