# Generated by Django 3.0.3 on 2020-03-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0006_merge_20200310_2021'),
        ('SIS', '0006_merge_20200310_1834'),
    ]

    operations = [
    ]
