# Generated by Django 3.0.3 on 2020-03-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS', '0007_merge_20200311_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions_list', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=50)),
                ('user_type', models.CharField(blank=True, choices=[('S', 'Student'), ('T', 'Teacher'), ('M', 'Management')], default='S', help_text='Type', max_length=1)),
                ('user_permissions', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(blank=True, choices=[('A', 'Absent'), ('P', 'Present'), ('E', 'Excused')], default='P', help_text='Attendance', max_length=1),
        ),
    ]
